/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import config.Session;
import config.Utility;
import config.db_connector;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mercy
 */
public class add_to_cart extends javax.swing.JDialog {
    
    db_connector conn = new db_connector();
    int productId;
    
    String name;
    double price;
    int max_stocks;
    
    /**
     * Creates new form add_to_cart
     */
    public add_to_cart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SwingUtilities.invokeLater(() -> getRootPane().requestFocus());
        
        Utility.setBorders(quantity_field);
        jLabel5.setIcon(resizeImage("/images/plus.png", jLabel5)); 
        jLabel6.setIcon(resizeImage("/images/minus.png", jLabel6)); 
        minimize_button.setIcon(Utility.resizeImage("/images/minimize-sign.png", minimize_button));
    }
    
    public void setProductId(int id){
        this.productId = id;
        loadInfo();
    }
    
    private void loadInfo(){
        try {
            ResultSet rs = conn.getData("SELECT name, price, stock FROM products WHERE id = " + productId);
            if (rs.next()) {
                product_name.setText(rs.getString("name"));
                price_label.setText("₱" + rs.getString("price"));
                max_stocks = rs.getInt("stock");
            }  
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private ImageIcon resizeImage(String path, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(label.getWidth() - 10, label.getHeight() - 10, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
    
    private void updateQuantity(JTextField quantityField, int change, int maxStock) {
        try {
            int current = Integer.parseInt(quantityField.getText().trim());
            int updated = current + change;

            if (updated < 1) updated = 1;
            if (updated > maxStock) updated = maxStock;

            quantityField.setText(String.valueOf(updated));
        } catch (NumberFormatException e) {
            quantityField.setText("1");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        product_name = new javax.swing.JLabel();
        increase_button = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        decrease_button = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        minimize_button = new javax.swing.JLabel();
        quantity_field = new javax.swing.JTextField();
        add_button = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cancel_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(134, 206, 203));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(Utility.blackish, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add to Cart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 340, 40));

        price_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        price_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price_label.setText("price");
        jPanel1.add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 340, 30));

        product_name.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        product_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_name.setText("product name");
        jPanel1.add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 340, 40));

        increase_button.setBackground(new java.awt.Color(255, 255, 255));
        increase_button.setBorder(javax.swing.BorderFactory.createLineBorder(Utility.darkermiku));
        increase_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                increase_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                increase_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                increase_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                increase_buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                increase_buttonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout increase_buttonLayout = new javax.swing.GroupLayout(increase_button);
        increase_button.setLayout(increase_buttonLayout);
        increase_buttonLayout.setHorizontalGroup(
            increase_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(increase_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        increase_buttonLayout.setVerticalGroup(
            increase_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(increase_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 30, 30));

        decrease_button.setBackground(new java.awt.Color(255, 255, 255));
        decrease_button.setBorder(javax.swing.BorderFactory.createLineBorder(Utility.darkermiku));
        decrease_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decrease_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decrease_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decrease_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decrease_buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                decrease_buttonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout decrease_buttonLayout = new javax.swing.GroupLayout(decrease_button);
        decrease_button.setLayout(decrease_buttonLayout);
        decrease_buttonLayout.setHorizontalGroup(
            decrease_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decrease_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        decrease_buttonLayout.setVerticalGroup(
            decrease_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(decrease_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 30, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Quantity:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 30));

        minimize_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(minimize_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 30, 30));

        quantity_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        quantity_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity_field.setText("1");
        quantity_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantity_fieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantity_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(quantity_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 30));

        add_button.setBackground(new java.awt.Color(19, 122, 127));
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                add_buttonMouseReleased(evt);
            }
        });
        add_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add to Cart");
        add_button.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 150, 30));

        jPanel1.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, 30));

        cancel_button.setBackground(new java.awt.Color(255, 255, 255));
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancel_buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseReleased(evt);
            }
        });
        cancel_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cancel");
        cancel_button.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 50, 30));

        jPanel1.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void increase_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increase_buttonMouseEntered
        increase_button.setBackground(Utility.miku);
    }//GEN-LAST:event_increase_buttonMouseEntered

    private void increase_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increase_buttonMouseExited
        increase_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_increase_buttonMouseExited

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void increase_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increase_buttonMousePressed
        increase_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_increase_buttonMousePressed

    private void increase_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increase_buttonMouseReleased
        increase_button.setBackground(Utility.miku);
    }//GEN-LAST:event_increase_buttonMouseReleased

    private void decrease_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrease_buttonMouseEntered
        decrease_button.setBackground(Utility.miku);
    }//GEN-LAST:event_decrease_buttonMouseEntered

    private void decrease_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrease_buttonMouseExited
        decrease_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_decrease_buttonMouseExited

    private void decrease_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrease_buttonMousePressed
        decrease_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_decrease_buttonMousePressed

    private void decrease_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrease_buttonMouseReleased
        decrease_button.setBackground(Utility.miku);
    }//GEN-LAST:event_decrease_buttonMouseReleased

    private void increase_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increase_buttonMouseClicked
        updateQuantity(quantity_field, 1, this.max_stocks);
    }//GEN-LAST:event_increase_buttonMouseClicked

    private void decrease_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decrease_buttonMouseClicked
        updateQuantity(quantity_field, -1, this.max_stocks);
    }//GEN-LAST:event_decrease_buttonMouseClicked

    private void quantity_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_fieldKeyPressed
     
    }//GEN-LAST:event_quantity_fieldKeyPressed

    private void quantity_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_fieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            evt.consume();
        }
        
        SwingUtilities.invokeLater(() -> {
            try {
                int value = Integer.parseInt(quantity_field.getText());
                if (value > max_stocks) {
                    quantity_field.setText(String.valueOf(max_stocks));
                }
            } catch (NumberFormatException e) {
                // ignore
            }
        });
    }//GEN-LAST:event_quantity_fieldKeyTyped

    private void add_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseEntered
        add_button.setBackground(new Color(14, 102, 107));
    }//GEN-LAST:event_add_buttonMouseEntered

    private void add_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseExited
        add_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_add_buttonMouseExited

    private void add_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMousePressed
        add_button.setBackground(new Color(12, 85, 90));
    }//GEN-LAST:event_add_buttonMousePressed

    private void add_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseReleased
        add_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_add_buttonMouseReleased

    private void cancel_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseEntered
        cancel_button.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_cancel_buttonMouseEntered

    private void cancel_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseExited
        cancel_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_cancel_buttonMouseExited

    private void cancel_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMousePressed
        cancel_button.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_cancel_buttonMousePressed

    private void cancel_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseReleased
        cancel_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_cancel_buttonMouseReleased

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        try {
            int quantity = Integer.parseInt(quantity_field.getText().trim());

            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
                return;
            }

            if (quantity > max_stocks) {
                JOptionPane.showMessageDialog(this, "Only " + max_stocks + " items available.");
                return;
            }

            db_connector db = new db_connector();
            String checkSql = "SELECT quantity FROM cart WHERE user_id = " + Session.getInstance().getUserId() + " AND product_id = " + productId;
            ResultSet rs = db.getData(checkSql);

            if (rs.next()) {
                int existingQty = rs.getInt("quantity");
                int newQty = existingQty + quantity;

                if (newQty > max_stocks) newQty = max_stocks;

                String updateSql = "UPDATE cart SET quantity = " + newQty + " WHERE user_id = " + Session.getInstance().getUserId() + " AND product_id = " + productId;
                db_connector.updateDatabase(updateSql);
            } else {
                String insertSql = "INSERT INTO cart (user_id, product_id, quantity) VALUES (" + Session.getInstance().getUserId() + ", " + productId + ", " + quantity + ")";
                db_connector.updateDatabase(insertSql);
            }

            CustomMessageDialog.showMessage(null, "Added to cart!", "Cart");
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Enter a valid number.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }//GEN-LAST:event_add_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_to_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_to_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_to_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_to_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                add_to_cart dialog = new add_to_cart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_button;
    private javax.swing.JPanel cancel_button;
    private javax.swing.JPanel decrease_button;
    private javax.swing.JPanel increase_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimize_button;
    private javax.swing.JLabel price_label;
    private javax.swing.JLabel product_name;
    private javax.swing.JTextField quantity_field;
    // End of variables declaration//GEN-END:variables
}
