/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import config.Utility;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class CustomYesNoDialog extends javax.swing.JDialog {
    
    private boolean choice = false;
    
    /**
     * Creates new form CustomMessageDialog
     * @param parent
     * @param message
     * @param title
     */
    public CustomYesNoDialog(java.awt.Frame parent, String message, String title) {
        super(parent, true);
        initComponents();
        setLabels();
        
        title_label.setText(title);
        message_label.setText("<html>" + message.replace("\n", "<br>") + "</html>");
    }
    
    public static boolean showConfirm(JFrame parent, String message, String title) {
        CustomYesNoDialog dialog = new CustomYesNoDialog(parent, message, title);
        dialog.setVisible(true);
        return dialog.choice;
    }
    
    private void setLabels() {
        JLabel[] labels = {close_button};
        String[] paths = {"close.png"};
        SwingUtilities.invokeLater(() -> {
            Utility.setIcons(labels, paths);
        });
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        close_button = new javax.swing.JLabel();
        yes_button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        no_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(134, 206, 203));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(Utility.darkermiku, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message_label.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        message_label.setText("message");
        message_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(message_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 60));

        jPanel2.setBackground(new java.awt.Color(19, 122, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        title_label.setText("title");
        jPanel2.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 190, 20));

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel2.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        yes_button.setBackground(new java.awt.Color(255, 255, 255));
        yes_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yes_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yes_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yes_buttonMouseExited(evt);
            }
        });
        yes_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yes");
        yes_button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanel1.add(yes_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, 30));

        no_button.setBackground(new java.awt.Color(255, 255, 255));
        no_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                no_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                no_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                no_buttonMouseExited(evt);
            }
        });
        no_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No");
        no_button.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanel1.add(no_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_close_buttonMouseClicked

    private void yes_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yes_buttonMouseEntered
        yes_button.setBackground(Utility.darkermiku);
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_yes_buttonMouseEntered

    private void yes_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yes_buttonMouseExited
        yes_button.setBackground(Color.WHITE);
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_yes_buttonMouseExited

    private void yes_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yes_buttonMouseClicked
        choice = true;
        this.dispose();
    }//GEN-LAST:event_yes_buttonMouseClicked

    private void no_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_no_buttonMouseClicked

    private void no_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_buttonMouseEntered
        no_button.setBackground(Color.RED);
        jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_no_buttonMouseEntered

    private void no_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_buttonMouseExited
        no_button.setBackground(Color.WHITE);
        jLabel2.setForeground(Color.BLACK);
    }//GEN-LAST:event_no_buttonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel message_label;
    private javax.swing.JPanel no_button;
    private javax.swing.JLabel title_label;
    private javax.swing.JPanel yes_button;
    // End of variables declaration//GEN-END:variables
}
