/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import config.Utility;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author manny
 */
public class CustomMessageDialog extends javax.swing.JDialog {

    /**
     * Creates new form CustomYesNoDialog
     * @param parent
     * @param message
     * @param title
     */
    public CustomMessageDialog(java.awt.Frame parent, String message, String title) {
        super(parent, true);
        initComponents();
    
        setLabels();
        title_label.setText(title);
        message_label.setText("<html>" + message.replace("\n", "<br>") + "</html>");
    }
    
    public static void showMessage(JFrame parent, String message, String title) {
        CustomMessageDialog dialog = new CustomMessageDialog(parent, message, title);
        dialog.setVisible(true);
    }
    
    private void setLabels() {
        JLabel[] labels = {close_button};
        String[] paths = {"close.png"};
        SwingUtilities.invokeLater(() -> {
            Utility.setIcons(labels, paths);
        });
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        close_button = new javax.swing.JLabel();
        ok_button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(134, 206, 203));
        jPanel1.setBorder(new javax.swing.border.LineBorder(Utility.darkermiku, 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message_label.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        message_label.setText("message");
        message_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(message_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 60));

        jPanel2.setBackground(new java.awt.Color(19, 122, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        title_label.setText("title");
        jPanel2.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 230, 20));

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel2.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        ok_button.setBackground(new java.awt.Color(255, 255, 255));
        ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ok_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ok_buttonMouseExited(evt);
            }
        });
        ok_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OK");
        ok_button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanel1.add(ok_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_close_buttonMouseClicked

    private void ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_ok_buttonMouseClicked

    private void ok_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseEntered
        ok_button.setBackground(Utility.darkermiku);
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_ok_buttonMouseEntered

    private void ok_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseExited
        ok_button.setBackground(Color.WHITE);
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_ok_buttonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel message_label;
    private javax.swing.JPanel ok_button;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
