/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Dialogs.add_product;
import Dialogs.verify_email;
import config.CustomScrollBarUI;
import config.Session;
import config.Utility;
import config.db_connector;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mercy
 */
public class products_view extends javax.swing.JInternalFrame {

    /**
     * Creates new form products_view
     */
    public products_view() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        
        JLabel[] labels = {product_pic};
        String[] paths = {"box.png"};
        SwingUtilities.invokeLater(() -> {
            Utility.setIcons(labels, paths);
        });
        
        bi.setNorthPane(null);
        
        display_products();
        styleProductTable();
    }
    
    private void display_products() {
        try {
            db_connector dbcon = new db_connector();
            ResultSet result = dbcon.getData(
                "SELECT id AS 'ID', name AS 'Product Name', price AS 'Price', stock AS 'Stock' " +
                "FROM products WHERE seller_id = '" + Session.getInstance().getUserId() + "'"
            );

            products_table.setModel(DbUtils.resultSetToTableModel(result));

            products_table.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
            products_table.getColumnModel().getColumn(1).setPreferredWidth(200);  // Product Name
            products_table.getColumnModel().getColumn(2).setPreferredWidth(90);   // Price
            products_table.getColumnModel().getColumn(3).setPreferredWidth(90);   // Stock

            products_table.getTableHeader().setBackground(new Color(19,122,127));

        } catch (SQLException e) {
            System.out.println("Can't Load Products: " + e.getMessage());
        }

        JScrollBar verticalBar = productScrollPane.getVerticalScrollBar();
        verticalBar.setUI(new CustomScrollBarUI());
        productScrollPane.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel() {{
            setBackground(Utility.blackish);
        }});
    }

    private void styleProductTable() {
        products_table.setRowHeight(27);
        products_table.setShowGrid(false);
        products_table.setGridColor(Color.LIGHT_GRAY);
        products_table.getTableHeader().setBackground(Color.BLACK);
        products_table.getTableHeader().setForeground(Color.WHITE);
        products_table.setBackground(Utility.blackish);
        products_table.setForeground(Color.BLACK);

        products_table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                           boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    label.setBackground(row % 2 == 0 ? Color.GRAY : Utility.grayish);
                } else {
                    label.setBackground(Utility.darkermiku);
                }

                return label;
            }
        });

        JTableHeader header = products_table.getTableHeader();
        header.setPreferredSize(new Dimension(products_table.getWidth(), 30));
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                           boolean hasFocus, int row, int column) {
                JLabel label = new JLabel(value.toString(), JLabel.LEADING);
                label.setOpaque(true);
                label.setBackground(Utility.blackish);
                label.setForeground(Color.WHITE);
                return label;
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productScrollPane = new javax.swing.JScrollPane();
        products_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        product_pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(610, 470));

        jPanel1.setBackground(new java.awt.Color(134, 206, 203));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productScrollPane.setViewportView(products_table);

        jPanel1.add(productScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 410));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(product_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        
        JDesktopPane desktopPane = this.getDesktopPane();
        if (desktopPane != null) {
            add_product.addProductDialog(desktopPane);
        }
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane productScrollPane;
    private javax.swing.JLabel product_pic;
    private javax.swing.JTable products_table;
    // End of variables declaration//GEN-END:variables
}
