
package theShop;

import Dialogs.CustomYesNoDialog;
import InternalFrames.account_main_page;
import InternalFrames.logs;
import InternalFrames.order_history;
import InternalFrames.users_table;
import config.Session;
import config.Utility;
import config.db_connector;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

public class Admin_Dashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form Admin_Dashboard
     */
    private JInternalFrame activeFrame = null;
    
    public Admin_Dashboard() {
        initComponents();
        
        JLabel[] labels = {logo, close_button, minimize_button, users_manage_pic, profile_pic, logout_pic, history_pic};
        String[] paths = {"leeeek.png", "close.png", "minimize-sign.png", "management.png", "user.png", "logout.png", "order.png"};
        Utility.setIcons(labels, paths);
        
        users_table users_table = new users_table();
        main_desktop.add(users_table).setVisible(true);
        
        users_button.setBackground(Utility.miku);
        activeFrame = users_table;
        
    }
    
    private void resetButtonColors() {
        profile_button.setBackground(Utility.darkermiku);
        users_button.setBackground(Utility.darkermiku);
        history_button.setBackground(Utility.darkermiku);
        logs_button.setBackground(Utility.darkermiku);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        profile_button = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        profile_pic = new javax.swing.JLabel();
        logout_button = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logout_pic = new javax.swing.JLabel();
        users_button = new javax.swing.JPanel();
        users_manage_pic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        history_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        history_pic = new javax.swing.JLabel();
        logs_button = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main_desktop = new javax.swing.JDesktopPane();
        minimize_button = new javax.swing.JLabel();
        close_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(Utility.grayish);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(19, 122, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DropXchange");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leeeek.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        profile_button.setBackground(Utility.darkermiku);
        profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_buttonMouseExited(evt);
            }
        });
        profile_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account Profile");
        profile_button.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));
        profile_button.add(profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel2.add(profile_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 40));

        logout_button.setBackground(Utility.darkermiku);
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_buttonMouseExited(evt);
            }
        });
        logout_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Logout");
        logout_button.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));
        logout_button.add(logout_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel2.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 190, 40));

        users_button.setBackground(Utility.darkermiku);
        users_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                users_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                users_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                users_buttonMouseExited(evt);
            }
        });
        users_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        users_button.add(users_manage_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Users Management");
        users_button.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 110, 40));

        jPanel2.add(users_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 40));

        history_button.setBackground(Utility.darkermiku);
        history_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                history_buttonMouseClicked(evt);
            }
        });
        history_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order Logs");
        history_button.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 40));
        history_button.add(history_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel2.add(history_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 40));

        logs_button.setBackground(Utility.darkermiku);
        logs_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logs_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logs_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logs_buttonMouseExited(evt);
            }
        });
        logs_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Check Logs");
        logs_button.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, -1, 120, 40));

        jPanel2.add(logs_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 190, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 190, 530);

        main_desktop.setBackground(new java.awt.Color(255, 255, 255));
        main_desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main_desktop.setDesktopManager(null);

        javax.swing.GroupLayout main_desktopLayout = new javax.swing.GroupLayout(main_desktop);
        main_desktop.setLayout(main_desktopLayout);
        main_desktopLayout.setHorizontalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        main_desktopLayout.setVerticalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(main_desktop);
        main_desktop.setBounds(190, 30, 610, 500);

        minimize_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-sign.png"))); // NOI18N
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(minimize_button);
        minimize_button.setBounds(740, 0, 30, 30);

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(close_button);
        close_button.setBounds(770, 0, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        Utility.logout(this);
    }//GEN-LAST:event_close_buttonMouseClicked

    private void profile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseClicked
        resetButtonColors(); 
        profile_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof account_main_page) { 
                try {
                    frame.setSelected(true); 
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        account_main_page acc = new account_main_page();
        main_desktop.add(acc);
        acc.setVisible(true);

        try {
            acc.setMaximum(true); 
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = acc;
    }//GEN-LAST:event_profile_buttonMouseClicked

    private void profile_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseEntered
        if (activeFrame == null || !(activeFrame instanceof account_main_page)) {
            profile_button.setBackground(Utility.miku);
        }
    }//GEN-LAST:event_profile_buttonMouseEntered

    private void profile_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseExited
        if (activeFrame == null || !(activeFrame instanceof account_main_page)) {
            profile_button.setBackground(Utility.darkermiku);
        }
    }//GEN-LAST:event_profile_buttonMouseExited

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
        boolean confirmed = CustomYesNoDialog.showConfirm(this, "Are you sure you want to Logout?", "Confirm Logout");
        if(!confirmed){
            return;
        }
        
        Session.getInstance().clearSession();
        
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_buttonMouseClicked

    private void logout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseEntered
        logout_button.setBackground(Utility.miku);
    }//GEN-LAST:event_logout_buttonMouseEntered

    private void logout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseExited
        
        logout_button.setBackground(Utility.darkermiku); 

    }//GEN-LAST:event_logout_buttonMouseExited

    private void users_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_buttonMouseClicked
        resetButtonColors();
        users_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof users_table) { 
                try {
                    frame.setSelected(true); 
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        users_table users = new users_table();
        main_desktop.add(users);
        users.setVisible(true);

        try {
            users.setMaximum(true); 
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = users;
    }//GEN-LAST:event_users_buttonMouseClicked

    private void users_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_buttonMouseEntered
        if (activeFrame == null || !(activeFrame instanceof users_table)) {
            users_button.setBackground(Utility.miku);
        }

    }//GEN-LAST:event_users_buttonMouseEntered

    private void users_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_buttonMouseExited
        if (activeFrame == null || !(activeFrame instanceof users_table)) {
            users_button.setBackground(Utility.darkermiku);
        }
    }//GEN-LAST:event_users_buttonMouseExited

    private void history_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_buttonMouseClicked
        resetButtonColors();
        history_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof order_history) { 
                try {
                    frame.setSelected(true); 
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        order_history history = new order_history();
        main_desktop.add(history);
        history.setVisible(true);

        try {
            history.setMaximum(true); 
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = history;
    }//GEN-LAST:event_history_buttonMouseClicked
    
    private void logs_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_buttonMouseClicked
        resetButtonColors();
        logs_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof logs) {
                try {
                    frame.setSelected(true);
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        logs logs = new logs();  // Logs is now an internal frame
        main_desktop.add(logs);
        logs.setVisible(true);

        try {
            logs.setMaximum(true);
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = logs;
    }//GEN-LAST:event_logs_buttonMouseClicked

    private void logs_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_buttonMouseEntered
        if (activeFrame == null || !(activeFrame instanceof logs)) {
            logs_button.setBackground(Utility.miku);
        }
    }//GEN-LAST:event_logs_buttonMouseEntered

    private void logs_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_buttonMouseExited
        if (activeFrame == null || !(activeFrame instanceof logs)) {
            logs_button.setBackground(Utility.darkermiku);
        }
    }//GEN-LAST:event_logs_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin_Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JPanel history_button;
    private javax.swing.JLabel history_pic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout_button;
    private javax.swing.JLabel logout_pic;
    private javax.swing.JPanel logs_button;
    private javax.swing.JDesktopPane main_desktop;
    private javax.swing.JLabel minimize_button;
    private javax.swing.JPanel profile_button;
    private javax.swing.JLabel profile_pic;
    private javax.swing.JPanel users_button;
    private javax.swing.JLabel users_manage_pic;
    // End of variables declaration//GEN-END:variables
}
