package theShop;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.awt.Font;
import java.awt.Image;
import java.awt.Window;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
        
//        setResizable(false);
        unFocus();
        
        user.setIcon(resizeImage("/images/user.png", user));
        pass.setIcon(resizeImage("/images/padlock.png", user));
        leek.setIcon(resizeImage("/images/leeeek.png", leek));
        show_pass.setIcon(resizeImage("/images/hidden.png", show_pass));
        
    }
    
    private ImageIcon resizeImage(String path, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(label.getWidth() - 17, label.getHeight() - 17, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
    
    private void unFocus(){
        setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getInitialComponent(Window window) {
                return null; 
            }

            @Override
            public Component getFirstComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getLastComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getDefaultComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getComponentAfter(Container focusCycleRoot, Component aComponent) { return null; }
            @Override
            public Component getComponentBefore(Container focusCycleRoot, Component aComponent) { return null; }

            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        registration = new javax.swing.JLabel();
        show_pass = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        registration1 = new javax.swing.JLabel();
        leek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 122, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 122, 127));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Back!");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 110, 260, 40);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(user);
        user.setBounds(50, 180, 30, 30);

        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        jPanel2.add(pass);
        pass.setBounds(50, 230, 30, 30);

        username.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText(" Enter username...");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(70, 180, 200, 30);

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton);
        LoginButton.setBounds(70, 280, 200, 30);

        registration.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        registration.setForeground(new java.awt.Color(0, 0, 204));
        registration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registration.setText("Sign up");
        registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrationMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registrationMousePressed(evt);
            }
        });
        jPanel2.add(registration);
        registration.setBounds(190, 310, 80, 20);

        show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hidden.png"))); // NOI18N
        show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_passMouseClicked(evt);
            }
        });
        jPanel2.add(show_pass);
        show_pass.setBounds(250, 230, 30, 30);

        password.setText(" Enter password...");
        password.setEchoChar((char) 0);
        password.setForeground(Color.GRAY);
        password.setFont(new Font("Arial", Font.ITALIC, 10));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(70, 230, 200, 30);

        registration1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        registration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registration1.setText("Don't have an account? ");
        registration1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registration1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registration1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registration1MousePressed(evt);
            }
        });
        jPanel2.add(registration1);
        registration1.setBounds(70, 310, 160, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 530));

        leek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leeeek.png"))); // NOI18N
        jPanel1.add(leek, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 240, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if (username.getText().equals(" Enter username...")) {
            username.setText("");  
            username.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (username.getText().isEmpty()) {
            username.setText(" Enter username...");
            username.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_usernameFocusLost

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        LoginButton.setBackground(new Color(134,206,203));
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        LoginButton.setBackground(Color.WHITE);
    }//GEN-LAST:event_LoginButtonMouseExited

    private void registrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseEntered
        registration.setForeground(new Color(134,206,203));
    }//GEN-LAST:event_registrationMouseEntered

    private void registrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseExited
        registration.setForeground(new Color(0,0,204));
    }//GEN-LAST:event_registrationMouseExited

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (password.getText().equals(" Enter password...")) {
            password.setText("");
            password.setEchoChar('•');
            password.setForeground(Color.BLACK);
            password.setFont(new Font("Arial", Font.PLAIN, 10));
        }   
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (password.getText().isEmpty()) {
            password.setText(" Enter password...");
            password.setEchoChar((char) 0);
            password.setForeground(Color.GRAY);
            password.setFont(new Font("Arial", Font.ITALIC, 10));
        }
    }//GEN-LAST:event_passwordFocusLost

    private void registrationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMousePressed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrationMousePressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    
    private boolean pass_visible = false;
    private void show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_passMouseClicked
        pass_visible = !pass_visible;
        String currentText = password.getText().trim();

        if (pass_visible) {
            if (!currentText.equals("Enter password...")) {
                password.setEchoChar((char) 0);
            }
            show_pass.setIcon(resizeImage("/images/eye.png", show_pass));
        } else {
            if (!currentText.equals("Enter password...")) {
                password.setEchoChar('•');
            }
            show_pass.setIcon(resizeImage("/images/hidden.png", show_pass)); 
        }
    }//GEN-LAST:event_show_passMouseClicked

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyReleased

    private void registration1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registration1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registration1MouseEntered

    private void registration1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registration1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registration1MouseExited

    private void registration1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registration1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_registration1MousePressed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
//        new db_test().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_LoginButtonMouseClicked
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leek;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registration;
    private javax.swing.JLabel registration1;
    private javax.swing.JLabel show_pass;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
