package theShop;


import config.db_connector;
import java.awt.*;
import java.awt.event.*;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.border.TitledBorder;

public class Register extends javax.swing.JFrame {
    
    db_connector conn = new db_connector();
    
    /** Creates new form Login */
    public Register() {
        initComponents();
        
        
        unFocus();
        setDefaultBorders();

        user.setIcon(resizeImage("/images/user.png", user));
        pass.setIcon(resizeImage("/images/padlock.png", user));
        leek.setIcon(resizeImage("/images/leeeek.png", leek));
        show_pass.setIcon(resizeImage("/images/hidden.png", show_pass));
        email_pic.setIcon(resizeImage("/images/email.png", email_pic));
        show_pass1.setIcon(resizeImage("/images/hidden.png", show_pass1));
        pass1.setIcon(resizeImage("/images/access.png", pass1));
        jLabel2.setIcon(resizeImage("/images/setting.png", jLabel2));
        
        ActionListener roleSelectionListener = (ActionEvent e) -> {
            role_panel.setBorder(BorderFactory.createTitledBorder(
                    BorderFactory.createLineBorder(Color.BLACK, 1), "Role"
            ));
        };

        user_role.addActionListener(roleSelectionListener);
        admin_role.addActionListener(roleSelectionListener);
    }
    
    private ImageIcon resizeImage(String path, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(label.getWidth() - 15, label.getHeight() - 15, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
    
    private void setDefaultBorders() {
    username_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    email_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    password_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    password1_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    TitledBorder roleBorder = BorderFactory.createTitledBorder(
        BorderFactory.createLineBorder(Color.BLACK, 1), "Role"
    );
    roleBorder.setTitleFont(new Font("Arial", Font.BOLD, 11));
    role_panel.setBorder(roleBorder);
    }
    
    private void unFocus(){
        setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getInitialComponent(Window window) {
                return null; 
            }

            @Override
            public Component getFirstComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getLastComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getDefaultComponent(Container focusCycleRoot) { return null; }
            @Override
            public Component getComponentAfter(Container focusCycleRoot, Component aComponent) { return null; }
            @Override
            public Component getComponentBefore(Container focusCycleRoot, Component aComponent) { return null; }

            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        register_button = new javax.swing.JButton();
        show_pass = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        email_input = new javax.swing.JTextField();
        email_pic = new javax.swing.JLabel();
        show_pass1 = new javax.swing.JLabel();
        password1_input = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JLabel();
        role_panel = new javax.swing.JPanel();
        admin_role = new javax.swing.JRadioButton();
        user_role = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        to_login = new javax.swing.JLabel();
        leek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 122, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 340));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, 40));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 30, 30));

        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 30, 30));

        username_input.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        username_input.setForeground(new java.awt.Color(153, 153, 153));
        username_input.setText(" Enter username...");
        username_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_inputFocusLost(evt);
            }
        });
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });
        jPanel2.add(username_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 30));

        register_button.setBackground(new java.awt.Color(255, 255, 255));
        register_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        register_button.setText("Fuck off");
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                register_buttonMousePressed(evt);
            }
        });
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 200, -1));

        show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hidden.png"))); // NOI18N
        show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_passMouseClicked(evt);
            }
        });
        jPanel2.add(show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, 30));

        password_input.setText(" Enter password...");
        password_input.setEchoChar((char) 0);
        password_input.setForeground(Color.GRAY);
        password_input.setFont(new Font("Arial", Font.ITALIC, 10));
        password_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_inputFocusLost(evt);
            }
        });
        jPanel2.add(password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 30));

        email_input.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        email_input.setForeground(new java.awt.Color(153, 153, 153));
        email_input.setText(" Enter email...");
        email_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_inputFocusLost(evt);
            }
        });
        email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_inputActionPerformed(evt);
            }
        });
        jPanel2.add(email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 30));

        email_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        jPanel2.add(email_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 30, 30));

        show_pass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hidden.png"))); // NOI18N
        show_pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pass1MouseClicked(evt);
            }
        });
        jPanel2.add(show_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 30, 30));

        password1_input.setText(" Confirm password...");
        password1_input.setEchoChar((char) 0);
        password1_input.setForeground(Color.GRAY);
        password1_input.setFont(new Font("Arial", Font.ITALIC, 10));
        password1_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password1_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password1_inputFocusLost(evt);
            }
        });
        password1_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                password1_inputMouseEntered(evt);
            }
        });
        password1_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1_inputActionPerformed(evt);
            }
        });
        jPanel2.add(password1_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 200, 30));

        pass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/access.png"))); // NOI18N
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 30, 30));

        role_panel.setBackground(new java.awt.Color(0, 0, 0));
        role_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N
        role_panel.setOpaque(false);
        role_panel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                role_panelFocusGained(evt);
            }
        });
        role_panel.setLayout(null);

        admin_role.setBackground(new java.awt.Color(134, 206, 203));
        buttonGroup1.add(admin_role);
        admin_role.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        admin_role.setForeground(new java.awt.Color(19, 122, 127));
        admin_role.setText("Admin");
        admin_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_roleActionPerformed(evt);
            }
        });
        role_panel.add(admin_role);
        admin_role.setBounds(120, 20, 60, 30);

        user_role.setBackground(new java.awt.Color(134, 206, 203));
        buttonGroup1.add(user_role);
        user_role.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        user_role.setForeground(new java.awt.Color(19, 122, 127));
        user_role.setText("User");
        role_panel.add(user_role);
        user_role.setBounds(20, 20, 60, 30);

        jPanel2.add(role_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 200, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 30, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Already have an account?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 160, -1));

        to_login.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        to_login.setForeground(new java.awt.Color(0, 0, 204));
        to_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to_login.setText("Sign in");
        to_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                to_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                to_loginMouseExited(evt);
            }
        });
        jPanel2.add(to_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 530));

        leek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leeeek.png"))); // NOI18N
        jPanel1.add(leek, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 240, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void username_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_inputFocusGained
        if (username_input.getText().equals(" Enter username...")) {
            username_input.setText("");  
            username_input.setForeground(Color.BLACK); 
        }
        username_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_username_inputFocusGained

    private void username_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_inputFocusLost
        if (username_input.getText().isEmpty()) {
            username_input.setText(" Enter username...");
            username_input.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_username_inputFocusLost

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_buttonActionPerformed

    private void register_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseEntered
        register_button.setBackground(new Color(134,206,203));
    }//GEN-LAST:event_register_buttonMouseEntered

    private void register_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseExited
        register_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_register_buttonMouseExited

    private void password_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_inputFocusGained
        if (password_input.getText().equals(" Enter password...")) {
            password_input.setText("");
            password_input.setEchoChar('•');
            password_input.setForeground(Color.BLACK);
            password_input.setFont(new Font("Arial", Font.PLAIN, 10));
            password_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        }   
    }//GEN-LAST:event_password_inputFocusGained

    private void password_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_inputFocusLost
        if (password_input.getText().isEmpty()) {
            password_input.setText(" Enter password...");
            password_input.setEchoChar((char) 0);
            password_input.setForeground(Color.GRAY);
            password_input.setFont(new Font("Arial", Font.ITALIC, 10));
        }
    }//GEN-LAST:event_password_inputFocusLost

    private void register_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMousePressed
        
    }//GEN-LAST:event_register_buttonMousePressed
    boolean pass_visible = false;
    private void show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_passMouseClicked
        pass_visible = !pass_visible;
        String currentText = password_input.getText().trim();

        if (pass_visible) {
            if (!currentText.equals("Enter password...")) {
                password_input.setEchoChar((char) 0);
            }
            show_pass.setIcon(resizeImage("/images/eye.png", show_pass));
        } else {
            if (!currentText.equals("Enter password...")) {
                password_input.setEchoChar('•');
            }
            show_pass.setIcon(resizeImage("/images/hidden.png", show_pass));
        }
    }//GEN-LAST:event_show_passMouseClicked

    private void email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_inputActionPerformed

    private void password1_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1_inputFocusGained
        if (password1_input.getText().equals(" Confirm password...")) {
            password1_input.setText("");
            password1_input.setEchoChar('•');
            password1_input.setForeground(Color.BLACK);
            password1_input.setFont(new Font("Arial", Font.PLAIN, 10));
        } 
        password1_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_password1_inputFocusGained

    private void password1_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1_inputFocusLost
        if (password1_input.getText().isEmpty()) {
            password1_input.setText(" Confirm password...");
            password1_input.setEchoChar((char) 0);
            password1_input.setForeground(Color.GRAY);
            password1_input.setFont(new Font("Arial", Font.ITALIC, 10));
        }
    }//GEN-LAST:event_password1_inputFocusLost
    boolean pass_visible1 = false;
    private void show_pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pass1MouseClicked
        pass_visible1 = !pass_visible1;
        String currentText = password1_input.getText().trim();

        if (pass_visible1) {
            if (!currentText.equals("Confirm password...")) {
                password1_input.setEchoChar((char) 0);
            }
            show_pass1.setIcon(resizeImage("/images/eye.png", show_pass1));
        } else {
            if (!currentText.equals("Confirm password...")) {
                password1_input.setEchoChar('•');
            }
            show_pass1.setIcon(resizeImage("/images/hidden.png", show_pass1));
        }
    }//GEN-LAST:event_show_pass1MouseClicked

    private void password1_inputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password1_inputMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_password1_inputMouseEntered

    private void email_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_inputFocusGained
        email_input.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        if (email_input.getText().equals(" Enter email...")) {
            email_input.setText("");  
            email_input.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_email_inputFocusGained

    private void email_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_inputFocusLost
        if (email_input.getText().isEmpty()) {
            email_input.setText(" Enter email...");
            email_input.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_email_inputFocusLost

    private void admin_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_roleActionPerformed

    private void to_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_loginMouseEntered
        to_login.setForeground(new Color(134,206,203));
    }//GEN-LAST:event_to_loginMouseEntered

    private void to_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_loginMouseExited
        to_login.setForeground(new Color(0,0,204));
    }//GEN-LAST:event_to_loginMouseExited

    private void to_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_loginMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_to_loginMouseClicked

    private void password1_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1_inputActionPerformed

    private void register_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseClicked
        
        String username = username_input.getText().trim();
        String email = email_input.getText().trim();
        String password = new String(password_input.getPassword());
        String password1 = new String(password1_input.getPassword());
        String role = "";
        
        if(username.isEmpty() || username.equals("Enter username...")) {
            username_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        
        if(password.isEmpty() || password.equals(" Enter password...")) {
            password_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        
        if(email.isEmpty() || email.equals("Enter email...") || !isValidEmail(email)) {
            email_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        
        if(password1.isEmpty() || password.equals(" Enter password...")) {
            password1_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }

        if(!user_role.isSelected() && !admin_role.isSelected()) {
            role_panel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(Color.RED, 2), "Role"
            ));
        }
        
        boolean pass_confirmed = Arrays.equals(password_input.getPassword(), password1_input.getPassword());
        if(!pass_confirmed){
            password1_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        
        if (user_role.isSelected()) {
            role = "user";
        } else if (admin_role.isSelected()) {
            role = "admin";
        }
        
        // idk wtf is ts tbh..
        try {
            if(username.isEmpty() || username.equals("Enter username...")){
            JOptionPane.showMessageDialog(null, "Please Enter a Username!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(email.isEmpty() || email.equals("Enter email...") || !isValidEmail(email)){
                if(email.isEmpty() || email.equals("Enter email...")){
                    JOptionPane.showMessageDialog(null, "Please Enter an Email!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter a Valid Email!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else if(password.isEmpty() || password.equals(" Enter password...")){
                JOptionPane.showMessageDialog(null, "Please Enter a Password!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(password.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(!pass_confirmed){
                JOptionPane.showMessageDialog(null, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(!user_role.isSelected() && !admin_role.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select a role!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(conn.fieldExists("username", username) || conn.fieldExists("email", email)){
                if(conn.fieldExists("username", username)){
                    username_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
                }
                if(conn.fieldExists("email", email)){
                    email_input.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
                }
                
                if(conn.fieldExists("username", username)){
                    JOptionPane.showMessageDialog(null, "Username already taken!", "Error", JOptionPane.ERROR_MESSAGE);
                }else if(conn.fieldExists("email", email)){
                    JOptionPane.showMessageDialog(null, "Email already used!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{

                conn.insertData("INSERT INTO `user` (`username`, `email`, `password`, `role`) VALUES ('"+username+"', '"+email+"', '"+password+"', '"+role+"')");
                JOptionPane.showMessageDialog(null, "Registered Successfully!");
                
                if(user_role.isSelected()){
                    new User_Dashboard().setVisible(true);
                }else if(admin_role.isSelected()){
                    new Admin_Dashboard().setVisible(true);
                }
                this.dispose();
            }
        } catch (SQLException e) {
            System.out.println("Can't Connect to Database: " + e.getMessage());
        }
    }//GEN-LAST:event_register_buttonMouseClicked
    
    private void role_panelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_role_panelFocusGained
        
    }//GEN-LAST:event_role_panelFocusGained
    
    private boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(emailRegex);
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin_role;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel email_pic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leek;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JPasswordField password1_input;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel role_panel;
    private javax.swing.JLabel show_pass;
    private javax.swing.JLabel show_pass1;
    private javax.swing.JLabel to_login;
    private javax.swing.JLabel user;
    private javax.swing.JRadioButton user_role;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables

}
