/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theShop;

import Dialogs.CustomYesNoDialog;
import InternalFrames.products_view;
import InternalFrames.account_main_page;
import config.Session;
import config.Utility;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author Mercy
 */
public class Seller extends javax.swing.JFrame {
    
    private JInternalFrame activeFrame = null;
    
    /**
     * Creates new form Seller
     */
    public Seller() {
        initComponents();
        
        Session.getInstance().setUserId(112);
        
        greet.setText("Seller: " + (Session.getInstance().getName() != null ? Session.getInstance().getName() : "NOT LOGGED IN"));
        
        JLabel[] labels = {logo, close_button, logout_pic, profile_pic};
        String[] paths = {"leeeek.png", "close.png", "logout.png", "user.png"};
        Utility.setIcons(labels, paths);
        
        products_view prods = new products_view();
        main_desktop.add(prods);
        prods.setVisible(true);
    }
    
    private void resetButtonColors() {
        profile_button.setBackground(Utility.darkermiku);
        products_button.setBackground(Utility.darkermiku);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close_button = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        products_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout_button = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logout_pic = new javax.swing.JLabel();
        profile_button = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        profile_pic = new javax.swing.JLabel();
        greet = new javax.swing.JLabel();
        main_desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 59, 62));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(190, 200, 209));
        jPanel1.setForeground(new java.awt.Color(55, 59, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        jPanel2.setBackground(new java.awt.Color(19, 122, 127));
        jPanel2.setPreferredSize(new java.awt.Dimension(190, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        products_button.setBackground(Utility.miku);
        products_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                products_buttonMouseClicked(evt);
            }
        });
        products_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Products");
        products_button.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 110, 40));

        jPanel2.add(products_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leeeek.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DropXchange");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        logout_button.setBackground(Utility.darkermiku);
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_buttonMouseExited(evt);
            }
        });
        logout_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Logout");
        logout_button.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 80, 40));
        logout_button.add(logout_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 40));

        jPanel2.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 190, 40));

        profile_button.setBackground(Utility.darkermiku);
        profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_buttonMouseExited(evt);
            }
        });
        profile_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Account Profile");
        profile_button.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 110, 40));
        profile_button.add(profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        jPanel2.add(profile_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 530));

        greet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        greet.setText("Seller: ");
        jPanel1.add(greet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 300, 40));

        javax.swing.GroupLayout main_desktopLayout = new javax.swing.GroupLayout(main_desktop);
        main_desktop.setLayout(main_desktopLayout);
        main_desktopLayout.setHorizontalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        main_desktopLayout.setVerticalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(main_desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 610, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_buttonMouseClicked

    private void products_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_buttonMouseClicked
        products_view prods = new products_view();
        main_desktop.add(prods);
        prods.setVisible(true);
    }//GEN-LAST:event_products_buttonMouseClicked

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
        boolean confirmed = CustomYesNoDialog.showConfirm(this, "Are you sure you want to Logout?", "Confirm Logout");
        if(!confirmed){
            return;
        }

        Session session = Session.getInstance();
        session.clearSession();

        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_buttonMouseClicked

    private void logout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseEntered
        logout_button.setBackground(Utility.miku);
    }//GEN-LAST:event_logout_buttonMouseEntered

    private void logout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseExited

        logout_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_logout_buttonMouseExited

    private void profile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseClicked
        resetButtonColors();
        profile_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof account_main_page) {
                try {
                    frame.setSelected(true);
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        account_main_page acc = new account_main_page();
        main_desktop.add(acc);
        acc.setVisible(true);

        try {
            acc.setMaximum(true);
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = acc;
    }//GEN-LAST:event_profile_buttonMouseClicked

    private void profile_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseEntered
        if (activeFrame == null || !(activeFrame instanceof account_main_page)) {
            profile_button.setBackground(Utility.miku);
        }
    }//GEN-LAST:event_profile_buttonMouseEntered

    private void profile_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseExited
        if (activeFrame == null || !(activeFrame instanceof account_main_page)) {
            profile_button.setBackground(Utility.darkermiku);
        }
    }//GEN-LAST:event_profile_buttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel greet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout_button;
    private javax.swing.JLabel logout_pic;
    private javax.swing.JDesktopPane main_desktop;
    private javax.swing.JPanel products_button;
    private javax.swing.JPanel profile_button;
    private javax.swing.JLabel profile_pic;
    // End of variables declaration//GEN-END:variables
}
