
package theShop;

import InternalFrames.*;
import config.Utility;
import config.db_connector;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

public class User_Dashboard extends javax.swing.JFrame {
    
    private JInternalFrame activeFrame = null;
    
    db_connector conn = new db_connector();
    
    private static int id;
    /**
     * Creates new form User_Dashboard
     * @param id
     */
    public User_Dashboard(int id) {
        initComponents();
        
        User_Dashboard.id = id;
        
        minimize_button.setIcon(Utility.resizeImage("/images/minimize-sign.png", minimize_button));
        close_button.setIcon(Utility.resizeImage("/images/close.png", close_button));
        profile_pic.setIcon(Utility.resizeImage("/images/user.png", profile_pic));
        
        account_profile profile = new account_profile(id);
        main_desktop.add(profile).setVisible(true);
        profile_button.setBackground(Utility.miku);
        activeFrame = profile;
    }
    
    private void resetButtonColors() {
        profile_button.setBackground(Utility.darkermiku);
//        users_button.setBackground(Utility.darkermiku);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logout_button = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profile_button = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        profile_pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close_button = new javax.swing.JLabel();
        minimize_button = new javax.swing.JLabel();
        main_desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(Utility.grayish);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(19, 122, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_button.setBackground(Utility.darkermiku);
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_buttonMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Logout");

        javax.swing.GroupLayout logout_buttonLayout = new javax.swing.GroupLayout(logout_button);
        logout_button.setLayout(logout_buttonLayout);
        logout_buttonLayout.setHorizontalGroup(
            logout_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_buttonLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        logout_buttonLayout.setVerticalGroup(
            logout_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 190, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leeeek.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DropXchange");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        profile_button.setBackground(Utility.darkermiku);
        profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_buttonMouseExited(evt);
            }
        });
        profile_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Account Profile");
        profile_button.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 40));
        profile_button.add(profile_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel2.add(profile_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 190, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 190, 530);

        jLabel2.setText("USER DASHBOARD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 0, 120, 30);

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(close_button);
        close_button.setBounds(770, 0, 30, 30);

        minimize_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-sign.png"))); // NOI18N
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(minimize_button);
        minimize_button.setBounds(740, 0, 30, 30);

        javax.swing.GroupLayout main_desktopLayout = new javax.swing.GroupLayout(main_desktop);
        main_desktop.setLayout(main_desktopLayout);
        main_desktopLayout.setHorizontalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        main_desktopLayout.setVerticalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(main_desktop);
        main_desktop.setBounds(190, 30, 610, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_buttonMouseClicked

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_buttonMouseClicked

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void logout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseEntered
        logout_button.setBackground(Utility.miku);
    }//GEN-LAST:event_logout_buttonMouseEntered

    private void logout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseExited
        logout_button.setBackground(Utility.darkermiku);
    }//GEN-LAST:event_logout_buttonMouseExited

    private void profile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseClicked
        resetButtonColors();
        profile_button.setBackground(Utility.miku);

        for (JInternalFrame frame : main_desktop.getAllFrames()) {
            if (frame instanceof account_profile) {
                try {
                    frame.setSelected(true); // Bring it to front
                } catch (PropertyVetoException e) {
                    System.out.println(e.getMessage());
                }
                return;
            }
        }

        if (activeFrame != null) {
            activeFrame.dispose();
        }

        account_profile acc = new account_profile(id);
        main_desktop.add(acc);
        acc.setVisible(true);

        try {
            acc.setMaximum(true);
        } catch (PropertyVetoException e) {
            System.out.println(e.getMessage());
        }

        activeFrame = acc;
    }//GEN-LAST:event_profile_buttonMouseClicked

    private void profile_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseEntered
        if (activeFrame == null || !(activeFrame instanceof account_profile)) {
            profile_button.setBackground(Utility.miku);
        }
    }//GEN-LAST:event_profile_buttonMouseEntered

    private void profile_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseExited
        if (activeFrame == null || !(activeFrame instanceof account_profile)) {
            profile_button.setBackground(Utility.darkermiku);
        }
    }//GEN-LAST:event_profile_buttonMouseExited
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User_Dashboard(User_Dashboard.id).setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout_button;
    private javax.swing.JDesktopPane main_desktop;
    private javax.swing.JLabel minimize_button;
    private javax.swing.JPanel profile_button;
    private javax.swing.JLabel profile_pic;
    // End of variables declaration//GEN-END:variables
}
